### ISSUE TITLE
Duplicate data fields

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#50]
In new cajal, we have eRAMONChannelDataType, and eRAMONDataType.

Do we really need both?  It's confusing - what if they are inconsistent?  Seems like we should do at a channel level and be done.

@gkiar @j6k4m8

**Comment by alexbaden** [comment]
The existing CAJAL infrastructure matched OCP exactly, so that's what I
copied. They could be combined back into one. However, that would mean we
would have to write a bunch of backend functions to take the data type from
OCP (for example, timeseries + 16bit) and convert it to CAJAL
(timeseries16).

On the one hand, having separate channel and data types is really nice. If
OCP decides to support 32 bit timeseries, no changes need to be made to
CAJAL. On the other hand, if you try and post with an unsupported datatype,
it's bad news.

I think it's out of scope for me to combine them again. However, I'd be
willing to help write some validation functions to prevent unsupported type
combinations.

Also, MATLAB enumerations are just atrocious, so while this may seem
trivial, it's a lot of really boring, unpleasant work to get it to work
properly (combining into one).

**Comment by alexbaden** [comment]
I think this is a pretty complicated thing to change. The best you could do would be to combine them in a method somewhere, so you set one "type" and it automatically sets the channel and data type (whenever user setting type is required).

**Comment by wrgr** [comment]
Yea - agreed.  I think after working through the unit tests, we can fix this in documentation - fine for people to be able to handle.
