### ISSUE TITLE
Synapse Won't Upload 

### ISSUE THREAD

**Issue by aksimhal** [neurodata/CAJAL#64]
Here's the gist: 

https://gist.github.com/aksimhal/50d196267a9ef46af754

**Comment by aksimhal** [comment]
@willgray @alexbaden

**Comment by alexbaden** [comment]
This doesn't look like a CAJAL problem. 

```
(Pdb) p self.data.dtype
dtype('int64')
(Pdb) p write.data.dtype
*** NameError: NameError("name 'write' is not defined",)
(Pdb) p writedata.dtype
dtype('uint32')
```

It looks like you have int64 data in the database. I'm not sure what to do about this. Ping Kunal on Gitter?  I'm going to close this issue, since we're good on the CAJAL side (meaning once this is fixed, it won't happen again).

If this token data doesn't mean anything, just create a new token and you shouldn't have any issues.
