### ISSUE TITLE
basicWrapper.py runtime error 

### ISSUE THREAD

**Issue by aksimhal** [neurodata/CAJAL#7]
When running the basicWrapper file (`python basicWrapper.py basicWrapperTestMFile.m '4.4' mystr '[2, 2, ; 3, 2]' 'true'` ), the matlabinit file generates an error.  However, I'm not sure when/how that file is called in the first place.  Error message: 

error message: 

```

@@@ MATLAB ERROR - 22-Mar-2015 13:44:18 @@@

Identifier: MatlabInit:FunctionHidden
Message: Another function appears to be hidding the method are are attempting to execute on the MATLAB search path.  Please verify.  Result of which: /Users/anish/Documents/Connectome/OCP_API/api/matlab/wrapper/basicWrapperTestMFile.m
Cause:
Stack:

 File: /Users/anish/Documents/Connectome/OCP_API/api/matlab/wrapper/matlabInit.m 
 Method: matlabInit 
 Line: 68 

@@@ MATLAB ERROR - 22-Mar-2015 13:44:18 @@@
                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                   R2014b (8.4.0.150421) 64-bit (maci64)
                             September 15, 2014


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.


System Host Name: Anishs-MacBook-Pro.local



Function Called: /Users/anish/Documents/Connectome/OCP_API/api/basicWrapperTestMFile.m
```

**Comment by wrgr** [comment]
Thanks!

Two things:
1.  Strongly recommend that you integrate on a CentOS virtual box, rather
   than a mac.  Although things are cross-platform, developing on a mac is
   likely to cause integration headaches later.
2.  Matlab has an order it looks for things (folders on your path).  What
   the error message is saying is that you are trying to call:

Function Called:
/Users/anish/Documents/Connectome/OCP_API/api/basicWrapperTestMFile.m

but this:   Result of which: /Users/anish/Documents/
Connectome/OCP_API/api/matlab/wrapper/basicWrapperTestMFile.m

has path precedence. So you are getting an error, which we included in the
API as an error check (to prevent bad things from happening).

If that doesn't help, let us know!

Best,
Will

**Comment by aksimhal** [comment]
(1) will do! 

(2) I still don't understand the cause/solution of the error - sorry! 

Thanks Will!

**Comment by wrgr** [comment]
What specifically is confusing, so we can help?  Basically, you need to
properly specify your paths, so that you are calling the function you
intend to call.  You can do this by setting environment variables and using
relative paths...as a short term workaround, you can use a hardcoded path.

You call:

python basicWrapper.py basicWrapperTestMFile.m '4.4' mystr '[2, 2, ; 3, 2]'
'true' )

But the basicWrapperTestMFile.m file is shadowed on your path by another
version of the file (see my other message).  Something like the following
thread might also be useful:
http://www.mathworks.com/matlabcentral/newsreader/view_thread/254911

Without seeing your setup, an easy way to understand the error is to run:

 python basicWrapper.py /Users/anish/Documents/
Connectome/OCP_API/api/matlab/wrapper/basicWrapperTestMFile.m '4.4' mystr
'[2, 2, ; 3, 2]' 'true'

This should solve this error, but is obviously not portable, so you'll want
to use variables and relative paths so that you don't need the full
absolute path in my example above.

Best,
Will

**Comment by aksimhal** [comment]
ah - understood! Thanks so much!
