### ISSUE TITLE
"oldchannel" support 

### ISSUE THREAD

**Issue by aksimhal** [neurodata/CAJAL#71]
CAJAL doesn't support 'oldchannel' as a data type which prevents access to the Chessboard Dataset.  Any file which does a type check is affected. 

I can provide more information as needed - thanks!

**Comment by wrgr** [comment]
I propose the following fix: 

Add enumeration type oldchannel in eRAMONChannelType

This works.  If we go this way, I recommend that we add an explicit warning that this project shouldn't be used for upload - if so, data corruption may result.  

Perhaps on line 327 of RAMONBase?  

@alexbaden - agree?  disagree? 
@kunallillaney @jovo @j6k4m8 

If we agree, I'll branch and pull request.  Will take me 10 minutes.

**Comment by alexbaden** [comment]
Disagree.

1) It's not that complicated to convert oldchannel projects to the new
schema. Just a few SQL queries, as far as I can tell. I did this
successfully with some AT data on the brainviz. Sure, it will take awhile,
but the sooner we start the faster it will be done...

2) It's not as simple as adding the enumeration in ChannelType -- you have
to know how to handle data of that type. It requires changing all calls
that check against eRAMONChannelType.

3) It's unclear whether oldchannel follows the current schema in terms of
packaging of HDF5 files (do the files still have /channel/ as the
groupname? if not, no CAJAL calls will work), etc.

If you want to try, I'll do my best to support. But I suspect the 10
minutes will increase exponentially as you dig in.

Alex

**Comment by wrgr** [comment]
@alexbaden's solution is much better technically, in my opinion.   Will
require time from @randalburns @kunallillaney, but not too much.

My solution is hacky, but will get us back to science in 10 minutes.
Fixing CAJAL in general is the wrong answer.  @alexbaden, you're right that
this only fixes image download, but this is actually the only query we want
to support with old channel.

So +1 to alex's answer, but need some answer pretty quick because we are
holding up Anish.

@jovo - care to opine?

Best,
Will

**Comment by kunallillaney** [comment]
@randalburns and I spent a bunch of time making this oldchannel support possible because what is proposed by @alexbaden is unfeasible and dangerous. Old channel hdf5 cutout format is the same as all other cutouts. Your solution is the correct fix in my opinion, I would strongly recommend against changing mysql schema but you guys are free to do so yourselves.

**Comment by alexbaden** [comment]
Why is it infeasible and dangerous? Create a new database with the new
schema, copy the old tables over, then run select zidx, blob from ...
insert into ...

Alex

**Comment by kunallillaney** [comment]
Unfeasible:
a. This is a different schema.
b. Multi-terabytes of data
c. Multiple Projects.
Dangerous:
a. Different schema with different keys

But if you think otherwise then you are free to pursue it yourself. I wrote a solution which I thought was the right way to deal with this data.

**Comment by wrgr** [comment]
dealing with on individual project basis.  no change to cajal planned.
